basicPipeline {
    PROFILE = "DockerOnly"
}

if ("master".equals(env.GIT_BRANCH)) {
    def label = "publish_k8s_operator-${UUID.randomUUID().toString()}"
    podCreator.initMain(label: label) {
        node(label) {
            wrapper.wrappedStage {
            withCredentials([
                string(credentialsId: 'GITHUB_TOKEN', variable: 'GITHUB_TOKEN'),
                string(credentialsId: 'ENFORCER_SECRET', variable: 'ENFORCER_SECRET'),
                string(credentialsId: 'SLACK_TOKEN', variable: 'SLACK_API_TOKEN')
            ]) {
                    stage('Publish External'){
                        container('rookout-helm') {
                            withCredentials([
                                    usernamePassword(credentialsId: 'DOCKERHUB', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')
                            ]) {
                                githubWrapper.clone(repo: 'rookout-k8s-operator', branchToClone: 'master', workDirToRepo: "true") {
                                    sh """
                                        # Auto publishing operator images if the last commit message indicates on external docker version update
                                        if git --no-pager log -1 | grep "Updated Docker external version to"; then
                                          echo "Auto publishing external images"
                                          make publish-operator
                                        else
                                          echo "not publishing to dockerhub"
                                        fi
                                    """
                                }
                            }
                        }
                    }
                }
            }
            notifyOpsgenie {}
        }
    }
}